### ISSUE TITLE
Facilitate releases

### ISSUE THREAD

**Issue by proc-2** [techno-solutionist-collective/dreadlocks#28]
First idea that crosses my mind: create a script (or use existing solution) that automates patch/minor/major version number bumping, tagging (version + latest), pushing/replacing tags on remote. Might be a good idea to centralize the definition of the latest version (currently spread across at least `pyproject.toml` and `docs/conf.py`).

**Comment by rikardn** [comment]
Perhaps using the same solution as Pharmpy (bumpversion).

**Comment by rikardn** [comment]
Seems like you are correct.
